### ISSUE TITLE
Missing Y Part

### ISSUE THREAD

**Issue by Crstll** [thomasfjen/enderwire_nonpro#3]
Hi , where I found the extension for Y profile ?
![2023-08-29_163304](https://github.com/thomasfjen/enderwire_nonpro/assets/62156128/22cf1096-45c6-44a0-8f53-5891ae204368)
Thanks :)

**Comment by thomasfjen** [comment]
Hey!
That's not the up-to-date model anymore, it got updated with a belt tensioner.

If you want to use old model without y tensioner then you would need to export the model yourself.
