### ISSUE TITLE
Minor discrepancies between bed_carriage_bolt_on.stl & enderwire_non_pro_asm.stp

### ISSUE THREAD

**Issue by thisiskeithb** [thomasfjen/enderwire_nonpro#4]
I wanted to add a 0.4mm chamfer to bottom face of `bed_carriage_bolt_on.stl` for improved printability, so I made the changes to `BED_PLATE_2` in `enderwire_non_pro_asm.stp` and exported the new model, but I noticed some minor discrepancies between what's in CAD and `bed_carriage_bolt_on.stl` provided in this repo.

The differences are minor, but they are not identical. Which is one is correct?

`BED_PLATE_2` from `enderwire_non_pro_asm.stp`:

![image](https://github.com/thomasfjen/enderwire_nonpro/assets/13375512/f9fc671e-09b1-438e-b4d1-686c9c14e677)

Pre-exported `bed_carriage_bolt_on.stl`:

![image](https://github.com/thomasfjen/enderwire_nonpro/assets/13375512/6ccfa7ca-d8ba-4646-ae2d-fa8a73257cb4)

**Comment by thomasfjen** [comment]
> I wanted to add a 0.4mm chamfer to bottom face of `bed_carriage_bolt_on.stl` for improved printability, so I made the changes to `BED_PLATE_2` in `enderwire_non_pro_asm.stp` and exported the new model, but I noticed some minor discrepancies between what's in CAD and `bed_carriage_bolt_on.stl` provided in this repo.
> 
> The differences are minor, but they are not identical. Which is one is correct?
> 
> `BED_PLATE_2` from `enderwire_non_pro_asm.stp`:
> 
> ![image](https://private-user-images.githubusercontent.com/13375512/310711548-f9fc671e-09b1-438e-b4d1-686c9c14e677.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDEzNzAsIm5iZiI6MTcwOTgwMTA3MCwicGF0aCI6Ii8xMzM3NTUxMi8zMTA3MTE1NDgtZjlmYzY3MWUtMDliMS00MzhlLWI0ZDEtNjg2YzljMTRlNjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA4NDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZWU5OWE0ZWJiNTlkODJhYmJhOThhMjRiMTdiNDA5ODc3MWRlZDA2MDY2ZmZiY2QxZmZjZmEyMjgxNDMwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vutmjuDWaAyUMS2bUPjepTk0jNDWKqK7GLrZk9eJ2WA)
> 
> Pre-exported `bed_carriage_bolt_on.stl`:
> 
> ![image](https://private-user-images.githubusercontent.com/13375512/310711583-6ccfa7ca-d8ba-4646-ae2d-fa8a73257cb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDEzNzAsIm5iZiI6MTcwOTgwMTA3MCwicGF0aCI6Ii8xMzM3NTUxMi8zMTA3MTE1ODMtNmNjZmE3Y2EtZDhiYS00NjQ2LWFlMmQtZmE4YTczMjU3Y2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA4NDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNmY3ZmQ5MTk0MTBiYTFkYjY1ODg0YjhlM2M1Y2Y3MDM1MDMzY2JjYjUxZTUxYWNjYzNiNDY0YTZhNzlkMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wYjLi35VC-w4zQx8qpnLds_E82ELWv2yYwRFLeI6mRw)

Hey! Yes there are some differences, i don't know what happend there or if i had a different revision at some point.

Checking my lasted files there are some minor differences and not exactly how i want it to be:
![grafik](https://github.com/thomasfjen/enderwire_nonpro/assets/47940833/41b4f85a-d201-4456-9de1-297a9325709b)

There is some play on one side when using the wheel holes, as the holes are bigger because of the excentric nuts and should cover the minor differences.

If i find time i'll fix the part and reupload the cad and stl.

**Comment by thomasfjen** [comment]
I just fixed the thing you mentioned with the update:
https://github.com/thomasfjen/enderwire_nonpro/commit/a3b6391bcf7a07d493456b47ed8711a2c6669d34

> I wanted to add a 0.4mm chamfer to bottom face of `bed_carriage_bolt_on.stl` for improved printability, so I made the changes to `BED_PLATE_2` in `enderwire_non_pro_asm.stp` and exported the new model, but I noticed some minor discrepancies between what's in CAD and `bed_carriage_bolt_on.stl` provided in this repo.
> 
> The differences are minor, but they are not identical. Which is one is correct?
> 
> `BED_PLATE_2` from `enderwire_non_pro_asm.stp`:
> 
> ![image](https://private-user-images.githubusercontent.com/13375512/310711548-f9fc671e-09b1-438e-b4d1-686c9c14e677.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDUwMTIsIm5iZiI6MTcxMTcwNDcxMiwicGF0aCI6Ii8xMzM3NTUxMi8zMTA3MTE1NDgtZjlmYzY3MWUtMDliMS00MzhlLWI0ZDEtNjg2YzljMTRlNjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MzE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMGMxYjYwYjllMjZmNjBlZjkyNzRkOWY4NWJjYmVhZDgwNzcyMmYwNTRkODlkMzJlN2RjY2UyZTcyZGY3YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WTIqkWH0l6d3yQ9BvNqV97vCJO8jjoQqsKoaDC0iP0w)
> 
> Pre-exported `bed_carriage_bolt_on.stl`:
> 
> ![image](https://private-user-images.githubusercontent.com/13375512/310711583-6ccfa7ca-d8ba-4646-ae2d-fa8a73257cb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDUwMTIsIm5iZiI6MTcxMTcwNDcxMiwicGF0aCI6Ii8xMzM3NTUxMi8zMTA3MTE1ODMtNmNjZmE3Y2EtZDhiYS00NjQ2LWFlMmQtZmE4YTczMjU3Y2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MzE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYzgzOWQ0YWY5MjYwOWQxNzQyNTQ2YjhlNGI1ZjM4MzJlZjgwY2E5OWUwNzhhMjFhMGY0ODlhYjZjMWUxYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VYzJxJW-hJy_R52p_s9qswP6GvjVGVtgFTDW22N4Zuc)
