### ISSUE TITLE
Y-Chain_Bed-Mount_x1 source missing from CAD?

### ISSUE THREAD

**Issue by thisiskeithb** [thomasfjen/enderwire_nonpro#5]
I'd like to remix [`Y-Chain_Bed-Mount_x1.stl`](https://github.com/thomasfjen/enderwire_nonpro/blob/main/STLs/Y-Axis/Y-Chain_Bed-Mount_x1.stl) to use a generic cable chain with "Igus" mounting holes (two inline holes vs. three in a triangular layout), but I don't see this part in `enderwire_non_pro_asm.stp`:

<img width="1662" alt="image" src="https://github.com/thomasfjen/enderwire_nonpro/assets/13375512/78c80024-4c0c-49f7-b5f2-05ae1fa415c1">

Note: I also checked in the [boubounokefalos/Ender_SW repo](https://github.com/boubounokefalos/Ender_SW), but [`[a]_y_chain_bed_mount_generic.stl`](https://github.com/boubounokefalos/Ender_SW/blob/main/STLS/Gantry/Y%20Axis/%5Ba%5D_y_chain_bed_mount_generic.stl) is completely different than what is hosted here.

**Comment by thomasfjen** [comment]
> I'd like to remix [`Y-Chain_Bed-Mount_x1.stl`](https://github.com/thomasfjen/enderwire_nonpro/blob/main/STLs/Y-Axis/Y-Chain_Bed-Mount_x1.stl) to use a generic cable chain with "Igus" mounting holes (two inline holes vs. three in a triangular layout), but I don't see this part in `enderwire_non_pro_asm.stp`:
> <img alt="image" width="1662" src="https://private-user-images.githubusercontent.com/13375512/311466000-78c80024-4c0c-49f7-b5f2-05ae1fa415c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjM4NjIsIm5iZiI6MTcxMDA2MzU2MiwicGF0aCI6Ii8xMzM3NTUxMi8zMTE0NjYwMDAtNzhjODAwMjQtNGMwYy00OWY3LWI1ZjItMDVhZTFmYTQxNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA5MzkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOTQ3YTE5YTVmNWE1Y2JhYjE1MWI2YzAwNjEzODZjYTIxZGRhOTM5NTM3ZjgwNDEzY2NkNDVjZDA2NDIxODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Hu6Pj6fVwdgGJfPHF-qOU_ksVNFyISbpGxyAljSFpQ">
> 
> Note: I also checked in the [boubounokefalos/Ender_SW repo](https://github.com/boubounokefalos/Ender_SW), but [`[a]_y_chain_bed_mount_generic.stl`](https://github.com/boubounokefalos/Ender_SW/blob/main/STLS/Gantry/Y%20Axis/%5Ba%5D_y_chain_bed_mount_generic.stl) is completely different than what is hosted here.


You're right, looks that part went missing when exporting the STEP.
You can get it from the gizzle repo CAD :https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/Gizzle/ender-3_(pro)_switchwire

One thing more to add to my list.

**Comment by thisiskeithb** [comment]
> You can get it from the gizzle repo CAD

Thanks! I should have looked there since it's called out in the README 😄

Having "generic" and "Igus" versions of `Y-Chain_Bed-Mount_x1.stl` & `Y-Chain_Frame-Mount_x1.stl` would be a nice improvement so this repo has a little more parity with the `boubounokefalos/Ender_SW` since both cable chain versions are available for Y & Z in that repo.

**Comment by thomasfjen** [comment]
> > You can get it from the gizzle repo CAD
> 
> Thanks! I should have looked there since it's called out in the README 😄
> 
> Having "generic" and "Igus" versions of `Y-Chain_Bed-Mount_x1.stl` & `Y-Chain_Frame-Mount_x1.stl` would be a nice improvement so this repo has a little more parity with the `boubounokefalos/Ender_SW` since both cable chain versions are available for Y & Z in that repo.


Added the igus variants:
https://github.com/thomasfjen/enderwire_nonpro/commit/a3b6391bcf7a07d493456b47ed8711a2c6669d34

If you have anymore issues let me know :)
